source 'https://rubygems.org'
#ruby '2.2.3'
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'bootstrap-sass'
gem 'devise'
gem 'high_voltage'
gem 'mysql2'
gem 'simple_form'
gem 'thin'
gem 'upmin-admin'
gem 'will_paginate', '~>3.0.5'
gem 'will_paginate-bootstrap'
gem 'colorize'

#spreadsheet scripting import gems
#gem 'spreadsheet' #, '~>0.8'
gem 'nokogiri', '~>1.6'
gem 'builder'
gem 'hpricot'
gem 'oauth'
gem 'roo', '1.11.2'
gem 'google-spreadsheet-ruby'
gem 'zip-zip'
gem 'archive-zip'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
