# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d01ce0792c83d254b113e4d30c8753651c129940f9ca5f17a8e1a75ab9b6872207375d9eef69760b7db15eba5b14a01cc330686f6698d6a83006d6f04f792a97

test:
  domain_name: example.com 
  secret_key_base: fd2fbc26df58d9d6c775f310bf5c52325e3ee9596747191d230e0cd14c6fd8112ab1d915f84a3b88416c86af068bf5e0d597f9da04fa1b971fdccad039de3ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
#  domain_name: <%= ENV["DOMAIN_NAME"] %>
  domain_name: example.com
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: fd2fbc26df58d9d6c775f310bf5c52325e3ee9596747191d230e0cd14c6fd8112ab1d915f84a3b88416c86af068bf5e0d597f9da04fa1b971fdccad039de3ece
